
[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
# family = "FantasqueSansM Nerd Font"
family = "Google Sans Code NF"
style = "Regular"

[general]
import = ["~/.config/alacritty/rose-pine/rose-pine.toml"]
# import = ["~/.config/alacritty/gruvbox/gruvbox.toml"]
